### ISSUE TITLE
Address "ssh-rsa" deprecation in OpenSSH

### ISSUE THREAD

**Issue by stevenjohnstone** [Mirantis/mcc#348]
Ran into this in #347.

OpenSSH [plans to deprecate](https://www.openssh.com/txt/release-8.3) "ssh-rsa". Some distros are already moving in this direction. In particular, when STIGs are applied in RHEL, "ssh-rsa" is not allowed. Trouble is that golang.org/x/crypto SSH doesn't negotiate 

There's work on going for this upstream e.g. https://go-review.googlesource.com/c/crypto/+/360195. With the latest (golang.org/x/crypto v0.0.0-20211215153901-e495a2d5b3d3), negotiating ssh with "ssh-rsa" deprecated does not work with RSA keys.

**Comment by james-nesbitt** [comment]
no longer relevant. launchpad doesn't manage keys, and it can handle ed-25519 now.
