### ISSUE TITLE
Update Multipass example

### ISSUE THREAD

**Issue by nwneisen** [Mirantis/mcc#385]
I'm interested in using multipass for my local dev setup. I was already messing with using launchpad for it and then I saw you had an example. I ran it and noticed a couple small issues:

- `-mem` is being deprecated in favor of `-memory`
- `launchpad.yaml` requires a version for MKE
- Remove some config values that were hardcoded and throwing errors

After making these changes, I began trying it for dev work and ended up making a couple more changes:

- Use template files so that `startup.sh` can be reran without issues
- Check for already existing VMs and notify the user they are being reused

I have some other things that I'd like to add to make this more convenient to use but I figured I'd start here. Thanks for creating and sharing the project.

**Comment by james-nesbitt** [comment]
we are going to drop the examples soon, in favor of hosted terraform.
