### ISSUE TITLE
Launchpad cannot install MCR on Windows Server from a Windows workstation

### ISSUE THREAD

**Issue by rleap-m** [Mirantis/mcc#388]
## Reproducibility of the Issue
Always

## Test Environment

- Cloud: AWS
- Cluster Size: 1 Mgr; 1 Linux Worker; 1 Windows Worker
- MCR: 23.0.6
- Linux Platform: RHEL 8.4
- Windows Platform: Window Server 2022
- Launchpad binary: version: 1.5.2; commit: 0780228

## Regression
No

## Issue
When launchpad is being run from a Windows workstation and when there is a Windows node in the cluster, launchpad fails during MCR upload to the Windows node.

```sh
level=info msg="\x1b[32m==> Running phase: Upgrade Mirantis Container Runtime on the hosts\x1b[0m"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=info msg="[winrm] 18.116.35.74:5986: upgrading container runtime (20.10.9 -> 23.0.6)"
level=error msg="[winrm] 18.116.35.74:5986: failed to update container runtime -> All attempts fail:\n#1: upload failed: command failed: non-zero exit code 1 during upload\n#2: upload failed: command failed: non-zero exit code 1 during upload\n#3: upload failed: command failed: non-zero exit code 1 during upload\n#4: upload failed: command failed: non-zero exit code 1 during upload\n#5: upload failed: command failed: non-zero exit code 1 during upload\n#6: upload failed: command failed: non-zero exit code 1 during upload\n#7: upload failed: command failed: non-zero exit code 1 during upload\n#8: upload failed: command failed: non-zero exit code 1 during upload\n#9: upload failed: command failed: non-zero exit code 1 during upload\n#10: upload failed: command failed: non-zero exit code 1 during upload"
level=info msg="See C:\\Users\\rleap/.mirantis-launchpad/cluster/34EW4M/apply.log for more logs "
level=fatal msg="All attempts fail:\n#1: upload failed: command failed: non-zero exit code 1 during upload\n#2: upload failed: command failed: non-zero exit code 1 during upload\n#3: upload failed: command failed: non-zero exit code 1 during upload\n#4: upload failed: command failed: non-zero exit code 1 during upload\n#5: upload failed: command failed: non-zero exit code 1 during upload\n#6: upload failed: command failed: non-zero exit code 1 during upload\n#7: upload failed: command failed: non-zero exit code 1 during upload\n#8: upload failed: command failed: non-zero exit code 1 during upload\n#9: upload failed: command failed: non-zero exit code 1 during upload\n#10: upload failed: command failed: non-zero exit code 1 during upload"
```

## Steps to Reproduce
Note: I used the [system test toolbox](https://github.com/Mirantis/testing-eng/tree/main/system_test_toolbox/launchpad) project which prepares the AWS resources and `launchpad.yaml` file

1. Prepare AWS environment  for MKE (EC2 nodes, including Windows Server 2019 or 2022 node)
1. Prepare `launchpad.yaml` file to install MKE.  
1. Run `launchpad apply` from Windows admin workstation (Windows 10 or 11)

## Desired Results
Successful installation of MCR on Windows nodes

## Actual Results
Attempts to install MCR on Windows nodes fail during upload, launchpad aborts

## Notes/Extras
- It looks like the `Upload` function that's called from this [InstallMCR](https://github.com/Mirantis/mcc/blob/7e9e8d6642a3a909a9174ec770543ed80cc15f63/pkg/configurer/windows.go#L39) function is where it is failing.
- I am able to use WinRM to access the Windows node from my Windows workstation

## Attachments
- [apply.log](https://github.com/Mirantis/mcc/files/12147778/apply.log)
- [launchpad.yaml.txt](https://github.com/Mirantis/mcc/files/12147793/launchpad.yaml.txt)

**Comment by james-nesbitt** [comment]
winrm in k0s/rig has been updated. This is likely out of date.
