### ISSUE TITLE
Cloud configuration file is not allowed for vSphere

### ISSUE THREAD

**Issue by a-anokhin** [Mirantis/mcc#398]
**Issue:**

Running launchpad with an vSphere cloud configuration fails 
`msg="unable to run install step \"Deploy Kubernetes API Server\": unable to reconcile state of Kubernetes API Server component: unable to reconcile container state: unable to create container ucp-kube-apiserver: Error response from daemon: invalid mount config for type \"bind\": bind source path does not exist: /etc/kubernetes/vsphere.conf"`

Currently **openstack** is not allowed as a cloud provider and should be replaced with **vsphere**
https://github.com/Mirantis/mcc/blob/master/pkg/product/mke/phase/install_mke.go#L187

**Comment by james-nesbitt** [comment]
This issue looks to be stale to me.
