### ISSUE TITLE
[MCR] Verifying the Engine version is insufficient

### ISSUE THREAD

**Issue by corhere** [Mirantis/mcc#416]
After installing or upgrading MCR, Launchpad checks that the installed Docker Engine version matches the MCR version in the Launchpad manifest spec.
https://github.com/Mirantis/mcc/blob/58709b33231b95c7d959503c58c4edd6866ff1fc/pkg/product/mke/api/host.go#L146
https://github.com/Mirantis/mcc/blob/58709b33231b95c7d959503c58c4edd6866ff1fc/pkg/product/mke/phase/upgrade_mcr.go#L185-L187

That only asserts the expected version of the `dockerd` binary (distributed in the `docker-ee` package) is installed. It would not catch if the `containerd` or `runc` binaries (distributed in the `containerd.io` package), the `docker` CLI (`docker-ee-cli` package) or `rootlesskit` (`docker-ee-rootless-extras`) were the wrong versions. If launchpad is going to check, it should check everything.

The containerd, runc and rootlesskit versions cannot be inferred from the MCR version in the manifest spec. And the Engine version might not always exactly match the MCR version, either. We'd need some kind of manifest which maps MCR version to expected component versions.

**Comment by james-nesbitt** [comment]
we are going to drop all engine version detection.

The down side of this will be that we will need to always run the MCR installer, and will never be able to tell if MCR was upgraded - meaning that we will need to always restart MCR, even if it wasn't upgraded.

**Comment by corhere** [comment]
> meaning that we will need to always restart MCR, even if it wasn't upgraded.

Wait... why does Launchpad restart MCR? The Linux packages and `install.ps1` handle stopping and restarting the services on upgrade.

**Comment by james-nesbitt** [comment]
Good point.

So https://github.com/Mirantis/mcc/pull/522 removes the code that reacted to version detection, and at the same time have removed the MCR restart on upgrade.

I left in some of the functionality for forcing a restart, but may remove it in the future as well.
